// generated by deep-copy --type ImageSet -o ./domain/image_set_deepcopy.go ./domain; DO NOT EDIT.

package domain

// DeepCopy generates a deep copy of ImageSet
func (o ImageSet) DeepCopy() ImageSet {
	var cp ImageSet = o
	if o.BaseNameToImageFileMap != nil {
		cp.BaseNameToImageFileMap = make(map[string]ImageFile, len(o.BaseNameToImageFileMap))
		for k2, v2 := range o.BaseNameToImageFileMap {
			cp.BaseNameToImageFileMap[k2] = v2
		}
	}
	return cp
}
