@startuml Use case diagram
left to right direction

actor user

package wallshrink {
    usecase "compress"
    note top
        * scale down
        * convert image file format
        * reduce the quality
    endnote

    usecase "Specify target image files" as specify
    note bottom: specify by directory

    usecase "Check the results" as check
    note bottom
        * show files that have changed
        * SSIM
        * file size (data compression ratio)
    endnote

    compress ..> specify : include
    compress ..> check : include
}

user --> compress
