@startuml Conceptual Model
left to right direction

object ImageSet
object Path

object ImageFile
object Size
object Dimension
object ParentImageSetPath

object BaseName
object Stem
object Extension

object SSIM

note top of ImageSet: is directory

note right of Size: unit is "Bytes"
note right of Extension: includes "."
note right of Dimension: width * height

ImageSet "1"--"1" Path
ImageSet "1"--"*" ImageFile

ImageFile "1"--"1" Size
ImageFile "1"--"1" Dimension
ImageFile "1"--"1" BaseName
ImageFile "1"--"1" ParentImageSetPath

BaseName "1"--"1" Stem
BaseName "1"--"1" Extension

SSIM "1"--"2" ImageFile
