@startuml Conceptual Model
left to right direction

object Directory
object DirectoryPath

object File
object FileSize
object FileName
object FileExtension
object FileBaseName

object Image
object Dimension
object SSIM

note right of FileSize: unit is "Bytes"
note right of FileExtension: includes "."
note right of Dimension: width * height

' ファイルが未作成の場合、実データを持たないので、0..1かもしれない

Directory "1"--"1" DirectoryPath
Directory "1"--"*" File

File "1"--"1" FileName
File "1"--"1" FileSize
File "1"--"0..1" Image

FileName "1"--"1" FileBaseName
FileName "1"--"0..1" FileExtension

Image "1"--"1" Dimension
SSIM "1"--"2" Image
