@startuml Conceptual Model
left to right direction

object ImageSet
object Path

object ImageFile
object Size
object Dimension

object FileName
object FileBaseName
object FileExtension

object SSIM

note top of ImageSet: is directory

note right of Size: unit is "Bytes"
note right of FileExtension: includes "."
note right of Dimension: width * height

ImageSet "1"--"1" Path
ImageSet "1"--"*" ImageFile

ImageFile "1"--"1" Size
ImageFile "1"--"1" Dimension
ImageFile "1"--"1" FileName

FileName "1"--"1" FileBaseName
FileName "1"--"0..1" FileExtension

SSIM "1"--"2" ImageFile
